apiVersion: v1
kind: Service
metadata:
  name: minio-api-service
  namespace: minio-operator
spec:
  type: NodePort
  selector:
    app: minio-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30088